### PR TITLE
Set default exocom-port to 80

### PR DESCRIPTION
**Pull request by trushton**
resolves [#276](https://github.com/Originate/exosphere-sdk/issues/276)

@kevgo @hugobho @ben-goldberg

### CODE REVIEW

**Comment by hugobho** [comment]
@ben-goldberg put up a PR for this, the tests won't pass locally because port 80 is a reserved port. We have to run ExoCom in a Docker container during tests. See: https://github.com/Originate/exocom/pull/124

**Comment by kevgo** [comment]
Unless this solves a real problem, let's postpone this. We have other super urgent things to work on.

**Comment by trushton** [comment]
@hugobho yeah I just saw his PR after submitting this. I tried using sudo to run the cucumber command which works locally but no luck on travis. Putting this on hold for now as other things are taking priority.

**Comment by charlierudolph** [comment]
Closing as the issue is suppose to resolve was decided against

**Pull request closed without merging**
